In [6]:
import pandas as pd

In [11]:
path = "C:\\Users\\millen11\\Dropbox\\PC\\Documents\\academia\\rpi\\classes\\fall23\\introToML\\"
ps_df = pd.read_csv(path + "global_socieoeconomic_df.csv")
display(ps_df)

,Open,High,Low,Close,Volume,Change In Price (%),ECPI,CCPI,GSCPI,EPSI,...,"Country_Taiwan, China","Country_Tanzania, United Rep.",Country_Thailand,Country_Trinidad and Tobago,Country_Turkey,Country_TÃ¼rkiye,Country_Uganda,Country_Ukraine,Country_United Kingdom,Country_United States
0,3129.573975,3130.112061,3101.756104,3109.104980,101200,-0.654050,93.8,90.2,0.39,2.725238,...,False,False,False,False,False,False,False,False,False,False
1,3129.573975,3130.112061,3101.756104,3109.104980,101200,-0.654050,92.1,91.6,0.39,2.701171,...,False,False,False,False,False,False,False,False,False,False
2,3129.573975,3130.112061,3101.756104,3109.104980,101200,-0.654050,12.4,98.5,0.39,2.633433,...,False,False,False,False,False,False,False,False,False,False
3,3129.573975,3130.112061,3101.756104,3109.104980,101200,-0.654050,90.0,91.9,0.39,2.588454,...,False,False,False,False,False,False,False,False,False,False
4,3129.573975,3130.112061,3101.756104,3109.104980,101200,-0.654050,104.4,101.4,0.39,3.141094,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377849,2007.459961,2016.790039,2006.040039,2012.199951,45498400,0.236119,137.9,121.9,1.78,2.613156,...,False,False,False,False,False,False,True,False,False,False
377850,2007.459961,2016.790039,2006.040039,2012.199951,45498400,0.236119,697.0,308.3,1.78,2.614502,...,False,False,False,False,False,False,False,True,False,False
377851,2007.459961,2016.790039,2006.040039,2012.199951,45498400,0.236119,160.4,122.0,1.78,2.468536,...,False,False,False,False,False,False,False,False,False,True
377852,2007.459961,2016.790039,2006.040039,2012.199951,45498400,0.236119,112.2,121.1,1.78,2.607859,...,False,False,False,False,False,False,False,False,False,False
377853,2007.459961,2016.790039,2006.040039,2012.199951,45498400,0.236119,202.8,134.1,1.78,1.628675,...,False,False,False,False,False,False,False,False,False,False

In [15]:
#PS1: Do external factors affect the stock market, if so, how much is performance affected?
covid_df = pd.read_csv(path + "covid_df.csv")
covid_df = covid_df.drop(columns = ["Unnamed: 0"])
display(covid_df)

mean_price_change_covid_df = covid_df["Change In Price (%)"].mean()
print(mean_price_change_covid_df)

mean_price_change_ps_df = ps_df["Change In Price (%)"].mean()
print(mean_price_change_ps_df)

,Country,Date,ECPI,CCPI,GSCPI,EPSI,Open,High,Low,Close,Volume,Region,Change In Price (%),Month,Day of Week
0,Greece,2020-01-31,105.7,98.9,0.09,6.000000,3133.399902,3143.290039,3076.649902,3076.649902,0,NaN,-1.811132,Jan,Friday
1,Greece,2020-01-31,105.7,98.9,0.09,6.000000,7108.600098,7147.600098,7108.600098,7121.200195,1011496700,NaN,0.177251,Jan,Friday
2,Greece,2020-01-31,105.7,98.9,0.09,6.000000,7008.399902,7046.700195,7008.399902,7017.200195,756400,ASEAN & Oceania,0.125568,Jan,Friday
3,Greece,2020-01-31,105.7,98.9,0.09,6.000000,3938.800049,3952.530029,3901.580078,3907.610107,26161100,Europe,-0.791864,Jan,Friday
4,Greece,2020-01-31,105.7,98.9,0.09,6.000000,41146.558594,41154.488281,40671.011719,40723.488281,11500,South & West Asia,-1.028203,Jan,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87774,South Africa,2023-03-31,186.5,138.7,-1.18,1.639814,1775.050049,1802.699951,1775.050049,1802.479980,4525120000,US & Canada,1.545305,Mar,Friday
87775,South Africa,2023-03-31,186.5,138.7,-1.18,1.639814,3265.010010,3273.469971,3255.590088,3258.899902,333549200,ASEAN & Oceania,-0.187139,Mar,Friday
87776,South Africa,2023-03-31,186.5,138.7,-1.18,1.639814,4285.839844,4325.339844,4278.310059,4315.049805,36312200,Europe,0.681546,Mar,Friday
87777,South Africa,2023-03-31,186.5,138.7,-1.18,1.639814,15874.190430,15951.799805,15857.190430,15868.059570,2440300,East Asia,-0.038622,Mar,Friday
87778,South Africa,2023-03-31,186.5,138.7,-1.18,1.639814,19.209999,19.430000,18.520000,18.700001,0,NaN,-2.654859,Mar,Friday

-0.27686875076621686
-0.047721129686292996

In [3]:
'''
Model Selection:
  Models to be tested and/or selected--
  2. Gradient Boosting Classifier
  3. LightGBM
  4. RandomForest Classifier
  5. MLP Classifier
'''
#Model imports
from lightgbm import LGBMClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

In [ ]:
def evaluate_model(y_test, y_pred): #Gives evaluation metrics for model
  acc_score = accuracy_score(y_test, y_pred)
  print("Accuracy Score: {:.2f}", acc_score)

In [ ]:
#LightGBM Classifier

In [ ]:
#Linear Classifier

In [ ]:
#Gradient Boosting Classifier

In [ ]:
#Random Forest Classifier

In [ ]:
#MLP Classifier